# Generated by Django 5.2.7 on 2025-10-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='budget',
            new_name='tblBudget_user_id_8f863d_idx',
            old_name='core_budget_user_id_8d27de_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='tblTransact_user_id_d61085_idx',
            old_name='core_transa_user_id_190a3b_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='tblTransact_categor_37ebbe_idx',
            old_name='core_transa_categor_8fbb1e_idx',
        ),
        migrations.AlterModelTable(
            name='budget',
            table='tblBudget',
        ),
        migrations.AlterModelTable(
            name='category',
            table='tblCategory',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='tblTransaction',
        ),
    ]
