# Generated by Django 5.2.7 on 2025-11-01 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_budget_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction'),
        ),
    ]
