# Generated by Django 5.2.7 on 2025-11-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_category_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
    ]
