# Generated by Django 5.2.7 on 2025-11-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
    ]
