# Generated by Django 5.2.7 on 2025-11-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
