# Generated by Django 5.2.7 on 2025-11-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_budget_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Success', 'success'), ('Pending', 'pending'), ('Failed', 'failed')], default='Pending'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
