# Generated by Django 5.2.7 on 2025-11-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_transaction_status_transaction_tx_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
