# Generated by Django 5.2.7 on 2025-11-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(max_length=25),
        ),
    ]
