# Generated by Django 5.2.7 on 2025-12-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(default='BIRR', max_length=3),
        ),
    ]
